export enum Constants {
    APP_INIT = 'APP/INIT',
    LANG_UPDATE = 'LANG/UPDATE',
    SCREEN_RESIZE = 'SCREEN/RESIZE',
    SHOW_GLOBAL_SPIN = 'SHOW/GLOBAL_SPIN',
    DRAWER_CHANGE = 'DRAWER/CHANGE'
}
